name: Docker Publish (Beta Images)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [released]
  schedule:
    - cron: '0 8 * * 2'

jobs:
  build-beta-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      registry-repositories: "docker.io/mauriciodulce/php,ghcr.io/mauriciodulce/php"
      tag-prefix: "beta-"
      release-type: "testing"
    secrets: inherit